name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://MithiAngu:$HF_TOKEN@huggingface.com/spaces/MithiAngu/Afterschool main
